version: "2.1"
services:
  wger:
    build:
      context: .
    restart: always
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_USER=postgres
      - DB_HOST=wger_db
      - DB_PORT=5432
      - DB_NAME=postgres
      - SECRET_KEY=blahblah
      - SOCIAL_AUTH_FACEBOOK_KEY=${FB_KEY}
      - SOCIAL_AUTH_FACEBOOK_SECRET=${FB_SECRET}
      - SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=${GOOGLE_KEY}
      - SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=${GOOGLE_SECRET}
      - SOCIAL_AUTH_TWITTER_KEY=${TWITTER_KEY}
      - SOCIAL_AUTH_TWITTER_SECRET=${TWITTER_SECRET}
    networks:
      - wger_network
    depends_on:
      - wger_db

  wger_db:
    image: postgres:latest
    restart: always
    expose:
      - 5432
    networks:
      - wger_network

networks:
  wger_network:
    driver: bridge

