# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-28 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20180228_1214'),
        ('config', '0002_auto_20180223_1145'),
    ]

    operations = [
    ]
