# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-06 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='diary',
            field=models.CharField(choices=[('planned', 'Planned'), ('consumed', 'Consumed')], default='Planned', max_length=50),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='diary',
            field=models.CharField(choices=[('planned', 'Planned'), ('consumed', 'Consumed')], default='Planned', max_length=50),
        ),
    ]
