# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-06 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_auto_20180306_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='diary',
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='diary',
            field=models.CharField(choices=[('Planned', 'Planned'), ('Consumed', 'Consumed')], default='Planned', max_length=50),
        ),
    ]
