# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-06 11:54
from __future__ import unicode_literals

from django.db import migrations
import wger.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_auto_20180306_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='time',
            field=wger.utils.fields.Html5TimeField(blank=True, null=True, verbose_name='Time (approx)'),
        ),
    ]
