# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-06 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0009_mealitem_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealitem',
            name='time',
        ),
    ]
