# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-10 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0010_remove_mealitem_time'),
        ('nutrition', '0006_mealitem_time'),
    ]

    operations = [
    ]
