# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-28 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_auto_20180221_1158'),
        ('gym', '0007_auto_20180223_1145'),
    ]

    operations = [
    ]
