# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-28 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_merge'),
        ('gym', '0007_auto_20180228_1214'),
    ]

    operations = [
    ]
