# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.13 on 2018-03-07 09:45
=======
# Generated by Django 1.9.13 on 2018-03-07 11:42
>>>>>>> origin/develop
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('gym', '0007_auto_20180220_1515'),
        ('gym', '0009_merge'),
=======
        ('gym', '0009_merge'),
        ('gym', '0007_auto_20180220_1515'),
>>>>>>> origin/develop
    ]

    operations = [
    ]
