# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-07 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='wkt_session',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.WorkoutSession', verbose_name='Workout session'),
        ),
    ]
