# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-13 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_set_drop_set'),
        ('manager', '0012_workoutlog_wkt_session'),
    ]

    operations = [
    ]
